-- =====================================================
-- COMPLETE DATABASE SCHEMA FOR PET MANAGEMENT APP
-- =====================================================

-- 1. PETS TABLE
-- =====================================================
create table if not exists pets (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  name text not null,
  species text,
  breed text,
  age numeric,
  weight numeric,
  diet jsonb,
  license_number text,
  license_date date,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS Policies for pets
alter table pets enable row level security;

drop policy if exists "Users can view their own pets" on pets;
create policy "Users can view their own pets" on pets
  for select using (auth.uid() = user_id);

drop policy if exists "Users can insert their own pets" on pets;
create policy "Users can insert their own pets" on pets
  for insert with check (auth.uid() = user_id);

drop policy if exists "Users can update their own pets" on pets;
create policy "Users can update their own pets" on pets
  for update using (auth.uid() = user_id);

drop policy if exists "Users can delete their own pets" on pets;
create policy "Users can delete their own pets" on pets
  for delete using (auth.uid() = user_id);

-- 2. HEALTH RECORDS TABLE
-- =====================================================
create table if not exists health_records (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  pet_id bigint references pets(id) on delete cascade,
  type text not null, -- Vaccination, Vet Visit, Weight, Medication, Injury, Surgery
  title text,
  date date not null,
  next_due date,
  notes text,
  weight numeric,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS Policies for health_records
alter table health_records enable row level security;

drop policy if exists "Users can view their own health records" on health_records;
create policy "Users can view their own health records" on health_records
  for select using (auth.uid() = user_id);

drop policy if exists "Users can insert their own health records" on health_records;
create policy "Users can insert their own health records" on health_records
  for insert with check (auth.uid() = user_id);

drop policy if exists "Users can update their own health records" on health_records;
create policy "Users can update their own health records" on health_records
  for update using (auth.uid() = user_id);

drop policy if exists "Users can delete their own health records" on health_records;
create policy "Users can delete their own health records" on health_records
  for delete using (auth.uid() = user_id);

-- 3. BEHAVIORS TABLE
-- =====================================================
create table if not exists behaviors (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  pet_id bigint references pets(id) on delete cascade,
  issue text not null,
  remedy text,
  date date not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS Policies for behaviors
alter table behaviors enable row level security;

drop policy if exists "Users can view their own behavior logs" on behaviors;
create policy "Users can view their own behavior logs" on behaviors
  for select using (auth.uid() = user_id);

drop policy if exists "Users can insert their own behavior logs" on behaviors;
create policy "Users can insert their own behavior logs" on behaviors
  for insert with check (auth.uid() = user_id);

drop policy if exists "Users can update their own behavior logs" on behaviors;
create policy "Users can update their own behavior logs" on behaviors
  for update using (auth.uid() = user_id);

drop policy if exists "Users can delete their own behavior logs" on behaviors;
create policy "Users can delete their own behavior logs" on behaviors
  for delete using (auth.uid() = user_id);

-- 4. EXPENSES TABLE
-- =====================================================
create table if not exists expenses (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  amount numeric not null,
  category text not null, -- Food, Medical, Grooming, Toys, Other
  date date not null,
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS Policies for expenses
alter table expenses enable row level security;

drop policy if exists "Users can view their own expenses" on expenses;
create policy "Users can view their own expenses" on expenses
  for select using (auth.uid() = user_id);

drop policy if exists "Users can insert their own expenses" on expenses;
create policy "Users can insert their own expenses" on expenses
  for insert with check (auth.uid() = user_id);

drop policy if exists "Users can update their own expenses" on expenses;
create policy "Users can update their own expenses" on expenses
  for update using (auth.uid() = user_id);

drop policy if exists "Users can delete their own expenses" on expenses;
create policy "Users can delete their own expenses" on expenses
  for delete using (auth.uid() = user_id);

-- =====================================================
-- INDEXES FOR PERFORMANCE
-- =====================================================
create index if not exists pets_user_id_idx on pets(user_id);
create index if not exists health_records_user_id_idx on health_records(user_id);
create index if not exists health_records_pet_id_idx on health_records(pet_id);
create index if not exists behaviors_user_id_idx on behaviors(user_id);
create index if not exists behaviors_pet_id_idx on behaviors(pet_id);
create index if not exists expenses_user_id_idx on expenses(user_id);

-- =====================================================
-- VERIFICATION QUERIES (Run these to check if everything is set up)
-- =====================================================
-- Uncomment to verify tables exist:
-- select table_name from information_schema.tables where table_schema = 'public';

-- Uncomment to verify RLS policies:
-- select schemaname, tablename, policyname from pg_policies where schemaname = 'public';
